version: "3.7"

services:
  bitcoind:
    image: lncm/bitcoind:v22.0@sha256:37a1adb29b3abc9f972f0d981f45e41e5fca2e22816a023faa9fdc0084aa4507
    command: -regtest -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcauth=umbrel:5071d8b3ba93e53e414446ff9f1b7d7b$$375e9731abd2cd2c2c44d2327ec19f4f2644256fdeaf4fc5229bf98b778aafec
    volumes:
      - ${PWD}/data/bitcoin:/data/.bitcoin
    restart: on-failure
    stop_grace_period: 15m30s
    ports:
      - "18443:18443" # regtest
  server:
    build: .
    depends_on: [bitcoind]
    command: ["npm", "start"]
    restart: on-failure
    ports:
      - "3005:3005"
    environment:
      PORT: "3005"
      BITCOIN_HOST: "bitcoind"
      RPC_PORT: "18443" # - regtest
      RPC_USER: "umbrel"
      RPC_PASSWORD: "moneyprintergobrrr"
      BITCOIN_RPC_HIDDEN_SERVICE: "somehiddenservice.onion"
      BITCOIN_P2P_HIDDEN_SERVICE: "anotherhiddenservice.onion"
      DEVICE_DOMAIN_NAME: "test.local"